// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var BaseModel = struct {
	ID        field.Number[uint64]
	CreatedAt field.Number[int64]
	UpdatedAt field.Number[int64]
}{
	ID:        field.Number[uint64]{}.WithColumn("id"),
	CreatedAt: field.Number[int64]{}.WithColumn("created_at"),
	UpdatedAt: field.Number[int64]{}.WithColumn("updated_at"),
}
