// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"github.com/yockii/yunjin/internal/model"
	"gorm.io/cli/gorm/field"
)

var Project = struct {
	Name    field.String
	OwnerID field.Number[uint64]
	Tags    field.Slice[model.Tag]
}{
	Name:    field.String{}.WithColumn("name"),
	OwnerID: field.Number[uint64]{}.WithColumn("owner_id"),
	Tags:    field.Slice[model.Tag]{}.WithName("Tags"),
}
