// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package dao

import (
	"gorm.io/cli/gorm/field"
)

var User = struct {
	Username field.String
	Password field.String
	Email    field.String
}{
	Username: field.String{}.WithColumn("username"),
	Password: field.String{}.WithColumn("password"),
	Email:    field.String{}.WithColumn("email"),
}
